project:
  type: website

website:
  navbar:
    left:
      - href: aboutyou.ipynb
        text: About me
      - href: code.ipynb
        text: Code
      - href: data.qmd
        text: Data
      - href: introduction.qmd
        text: Introduction
      - href: datagather.ipynb
        text: Data Gathering
      - href: dataclean.ipynb
        text: Data Cleaning
      - href: dataexplore.ipynb
        text: Data Exploration
      - href: naive.ipynb
        text: Naïve Bayes
      - href: clustering.ipynb
        text: Clustering
      - href: dimreduction.ipynb
        text: Dimensionality reduction
      - href: decisiontree.ipynb
        text: Decision Trees
      - href: conclusions.ipynb
        text: Conclusions
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



