project:
  type: website

website:
  title: "DSAN 5000 Website Project by Zenan Wang"
  navbar:
    left:
      - href: aboutyou.qmd
        text: About me
      - href: code.qmd
        text: Code
      - href: introduction.qmd
        text: Introduction
      - href: datagather.qmd
        text: Data Gathering
      - href: dataclean.qmd
        text: Data Cleaning
      - href: dataexplore.qmd
        text: Data Exploration
      - href: clustering.qmd
        text: Clustering
      - href: dimreduction.qmd
        text: Dimensionality reduction
      - href: decisiontree.qmd
        text: Decision Trees
      - href: conclusion.qmd
        text: Conclusions
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



